'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'comments',
      [
        {
          id: 1,
          post_id: 2,
          applicant_id: 1,
          comment_content: '콤비네이션 피자 1판 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 2,
          post_id: 3,
          applicant_id: 1,
          comment_content: '비빔밥 2개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 3,
          post_id: 4,
          applicant_id: 1,
          comment_content: '떡볶이 제일 매운맛으로 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 4,
          post_id: 5,
          applicant_id: 1,
          comment_content:
            '아이스 아메리카노 3잔, 아이스 카페라떼 2잔 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 5,
          post_id: 3,
          applicant_id: 2,
          comment_content: '갈비탕 2개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 6,
          post_id: 4,
          applicant_id: 2,
          comment_content: '순한맛 떡볶이 1개, 튀김세트 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 7,
          post_id: 5,
          applicant_id: 2,
          comment_content:
            '뜨거운 고구마라떼 2잔, 허니브레드 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 8,
          post_id: 6,
          applicant_id: 2,
          comment_content: '새우초밥 12p, 연어초밥 12p 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 9,
          post_id: 4,
          applicant_id: 3,
          comment_content: '중간맛 떡볶이 1개, 쿨피스 2개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 10,
          post_id: 5,
          applicant_id: 3,
          comment_content:
            '뜨거운 아메리카노 4잔, 초코쿠키 4개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 11,
          post_id: 6,
          applicant_id: 3,
          comment_content: '모듬초밥 20p, 우동 2개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 12,
          post_id: 7,
          applicant_id: 3,
          comment_content: '간짜장 2개, 탕수육(소) 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 13,
          post_id: 5,
          applicant_id: 4,
          comment_content: '딸기 요거트 3잔, 딸기 쿠키 3개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 14,
          post_id: 6,
          applicant_id: 4,
          comment_content:
            '활어초밥 12p, 간장새우초밥 12p, 우동 2개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 15,
          post_id: 7,
          applicant_id: 4,
          comment_content: '삼선짬뽕 1개, 일반짜장 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 16,
          post_id: 8,
          applicant_id: 4,
          comment_content: '국물닭발 1개, 콜라 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 17,
          post_id: 6,
          applicant_id: 5,
          comment_content: '연어초밥 20p 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 18,
          post_id: 7,
          applicant_id: 5,
          comment_content: '볶음밥 2개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 19,
          post_id: 8,
          applicant_id: 5,
          comment_content: '야채곱창 1개, 사이다 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 20,
          post_id: 9,
          applicant_id: 5,
          comment_content: '허니콤보 1마리, 콜라 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 21,
          post_id: 7,
          applicant_id: 6,
          comment_content: '탕수육(대) 1개, 콜라 2개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 22,
          post_id: 8,
          applicant_id: 6,
          comment_content: '무뼈닭발 2개, 주먹밥 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 23,
          post_id: 9,
          applicant_id: 6,
          comment_content:
            '레드콤보 1마리, 치즈볼 1개, 콜라 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 24,
          post_id: 10,
          applicant_id: 6,
          comment_content:
            '모듬초밥 20p, 우동 1개, 콜라 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 25,
          post_id: 8,
          applicant_id: 7,
          comment_content:
            '국물닭발 1개, 주먹밥 1개, 사이다 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 26,
          post_id: 9,
          applicant_id: 7,
          comment_content: '허니순살 2마리, 콜라 2개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 27,
          post_id: 10,
          applicant_id: 7,
          comment_content: '활어초밥 20p, 음료수 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 28,
          post_id: 1,
          applicant_id: 7,
          comment_content:
            '황금 올리브 후라이드 1마리, 콜라 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 29,
          post_id: 9,
          applicant_id: 8,
          comment_content: '레드순살 1마리, 사이다 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 30,
          post_id: 10,
          applicant_id: 8,
          comment_content: '모듬초밥 12p, 연어초밥 20p 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 31,
          post_id: 1,
          applicant_id: 8,
          comment_content:
            '황금 올리브 양념 1마리, 사이다 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 32,
          post_id: 2,
          applicant_id: 8,
          comment_content: '고구마 피자 1판, 콜라 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 33,
          post_id: 10,
          applicant_id: 9,
          comment_content:
            '장어초밥 3p, 새우초밥 3p, 연어초밥 6p 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 34,
          post_id: 1,
          applicant_id: 9,
          comment_content: '순살 양념 1마리, 치킨 무 2개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 35,
          post_id: 2,
          applicant_id: 9,
          comment_content: '페퍼로니 피자 2판, 콜라 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 36,
          post_id: 3,
          applicant_id: 9,
          comment_content: '참치김밥 2개, 오징어덮밥 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 37,
          post_id: 1,
          applicant_id: 10,
          comment_content: '스모크치킨 1마리, 콜라 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 38,
          post_id: 2,
          applicant_id: 10,
          comment_content: '불고기 피자 2판 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 39,
          post_id: 3,
          applicant_id: 10,
          comment_content: '육개장 2개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 40,
          post_id: 4,
          applicant_id: 10,
          comment_content:
            '매운맛 떡볶이 1개, 오징어 튀김 2개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 41,
          post_id: 11,
          applicant_id: 1,
          comment_content: '쉬림프 피자 1판 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 42,
          post_id: 12,
          applicant_id: 1,
          comment_content:
            '매운맛 떡볶이 2개, 오징어 튀김 2개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 43,
          post_id: 13,
          applicant_id: 1,
          comment_content: '아이스 아메리카노 3잔 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 44,
          post_id: 14,
          applicant_id: 1,
          comment_content: '무뼈 닭발 1개, 주먹밥 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
        {
          id: 45,
          post_id: 15,
          applicant_id: 1,
          comment_content: '비빔밥 1개, 육개장 1개 같이 주문해주세요!',
          createdAt: new Date(),
          updatedAt: new Date(),
          // deletedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('comments', null, {});
  },
};
